### ISSUE TITLE
👀 Tracking: Data Analytics Questions

### ISSUE THREAD

**Issue by BryanPan342** [UCLA-Creative-Labs/watchdog#1]
### Overview:

Questions we need to ask ourselves about for Project Apps.

### Design & Implementation:

TBD

### Checklist:

- [ ] Percentage of people who reapply
- [ ] Age demographic
- [ ] Do certain demographics reapply more than others
- [ ] When do people usually apply?
- [ ] Are there any patterns in the application process
- [ ] How many people apply each quarter
- [ ] Do current project members reapply
- [ ] Do current project members turn into project leads? or apply to be a project lead?
- [ ] How do these change over time?
- [ ] Ratios of # of projects to applicants
- [ ] What type of projects do applicants usually apply for?

--- 
This is a 👀 Tracking Issue
